exports_files([
    "opencv-wstring-convert.patch",
    "opencv-msvc-copts.patch",
    "opencv-msvc-pthread.patch",
    "libtiff-drop-root-version-file.patch",
    "rules_flutter-subdir-app.patch",
    "rules_flutter-windows-rc.patch",
    "rules_flutter-shared-darwin-legacy-dup.patch",
    "rules_flutter-apple-plugin-lib-objc-deps.patch",
    "rules_flutter-apple-plugins-framework-import.patch",
])
