load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "server",
    srcs = glob([
        "src/**/*.cpp",
        "include/**/*.h",
    ]),
    includes = ["include"],
    deps = [
        "//proto:service_cc_grpc",
        "@grpc//:grpc++",
        "@opencv//:core",
        "@opencv//:imgproc",
        "@opencv//:imgcodecs",
        "@opencv//:objdetect",
        "@sqlite3",
        "@stdexec",
        "@cli11",
        "@spdlog",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "smoke_client",
    srcs = ["test/smoke_client.cpp"],
    deps = [
        "//proto:service_cc_grpc",
        "@grpc//:grpc++",
    ],
    visibility = ["//visibility:public"],
)
