load("@rules_proto//proto:defs.bzl", "proto_library")
load("@com_github_grpc_grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")

package(default_visibility = ["//visibility:public"])

# Base proto layer
proto_library(
    name = "service_proto",
    srcs = ["service.proto"],
)

# Compiles C++ bindings
cc_proto_library(
    name = "service_cc_proto",
    deps = [":service_proto"],
)

# Compiles C++ gRPC service/stub bindings
cc_grpc_library(
    name = "service_cc_grpc",
    srcs = [":service_proto"],
    deps = [":service_cc_proto"],
)
