load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_proto_grpc_cpp//:defs.bzl", "cpp_grpc_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "service_proto",
    srcs = ["service.proto"],
    deps = [
            "@protobuf//:timestamp_proto",
        ],
)

cpp_grpc_library(
    name = "service_cc_grpc",
    protos = [":service_proto"],
)
